# Generated by Django 5.2.4 on 2025-08-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='field_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_staff.fieldofstudy'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
