# Generated by Django 5.2.4 on 2025-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0004_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
