# Generated by Django 5.2.4 on 2025-08-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0006_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dorm_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
