# Generated by Django 5.2.4 on 2025-08-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0008_adminrecentactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrecentactions',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'admin_staff'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='guardian_number',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
