# Generated by Django 5.2.4 on 2025-08-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0009_alter_adminrecentactions_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='field_of_study',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_of_study_relate_name', to='admin_staff.fieldofstudy'),
        ),
    ]
