# Generated by Django 5.2.4 on 2025-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='95f35637ec9d4d099a0c97e3c4c839a6', max_length=40),
        ),
    ]
