# NOTE: Merge conflict resolved: kept main's default for 'code'; using the later timestamp from br-2.
# Generated by Django 5.2.4 on 2025-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='09f66895419443bfbbf4906bab7a364c', max_length=40),
        ),
    ]