# Generated by Django 5.2.4 on 2025-08-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='c6dd51023a5b4535a125ade55f812736', max_length=40),
        ),
    ]
