# Generated by Django 5.2.4 on 2025-08-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='2b352efd872b47bcb9960354161edaf5', max_length=40),
        ),
    ]
