# Generated by Django 5.2.4 on 2025-08-16 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancesession_code'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='9cb974244dd8466eb168783124322ed9', max_length=40),
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
