# Generated by Django 5.2.4 on 2025-08-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='b29da5cf16704482abe3321d8cce308e', max_length=40),
        ),
    ]
