# Generated by Django 5.2.4 on 2025-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancesession_code_lectureattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='682f3844db414264ac9b6f362d4e8eb1', max_length=40),
        ),
    ]
