# NOTE: Merge conflict resolved: kept main's dependency and default value; using later timestamp from br-2.
# Generated by Django 5.2.4 on 2025-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='3de3d87496a44bd69ef0acc3d28db49a', max_length=40),
        ),
    ]