# Generated by Django 5.2.4 on 2025-08-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='902c562b45fe4d4d80ddb05fc0f969ff', max_length=40),
        ),
    ]
