# Generated by Django 5.2.4 on 2025-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='f6dd6147eee546138baaa349795039e2', max_length=40),
        ),
    ]
