# Generated by Django 5.2.4 on 2025-08-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='ba58a579ac114a86977c970dd56b1a8b', max_length=40),
        ),
    ]
