# Generated by Django 5.2.4 on 2025-08-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='ac79097803054a01b9507ef6f1c2363b', max_length=40),
        ),
    ]
