# Generated by Django 5.2.4 on 2025-08-16 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancesession_code'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureattendance',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='attended_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='0dedb57839e244ac922dc92e1bd47edc', max_length=40),
        ),
        migrations.CreateModel(
            name='DiningAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField(default=False)),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
