# Generated by Django 5.2.4 on 2025-08-15 18:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancesession_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='program_name',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 15, 21, 12, 24, 19144)),
        ),
        migrations.AlterField(
            model_name='attendancerecored',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='6ce7644965794788a4b4036940d84876', max_length=40),
        ),
    ]
