# Generated by Django 5.2.4 on 2025-08-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_lectureattendance_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='04401d61c9a04c0e9cfc8daa52e9b272', max_length=40),
        ),
    ]
