# Generated by Django 5.2.4 on 2025-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='c86c15543aad4a8d97b0a61f76be0745', max_length=40),
        ),
    ]
