# Generated by Django 5.2.4 on 2025-08-16 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancesession_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='97cb561f560a4248801f09b67934a6d2', max_length=40),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 1, 41, 37, 950868)),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='type',
            field=models.CharField(choices=[('early', 'Early Comers'), ('dining', 'Dining Hall')], max_length=20),
        ),
    ]
