# Generated by Django 5.2.4 on 2025-08-18 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendancesession_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='6b365f7b472f45adad4518b1560aca01', max_length=40),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 14, 15, 39, 180243)),
        ),
    ]
