# Generated by Django 5.2.4 on 2025-08-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendancesession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='3f98bab445f74a3cae749f0ebefd429b', max_length=40),
        ),
    ]
