# Generated by Django 5.2.4 on 2025-08-18 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendancesession_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='title',
            field=models.CharField(default='Attendance Title', max_length=150),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='7bacc81a8c3b426c8f2b7bd60aa6b100', max_length=40),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 18, 16, 28, 437125)),
        ),
    ]
