# Generated by Django 5.2.4 on 2025-08-18 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancesession_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(default='9bf22fe3e5994aafac40c9527569d9c7', max_length=40),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 20, 15, 15, 557472)),
        ),
    ]
