# Generated by Django 5.2.4 on 2025-08-20 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_attendancesession_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='code',
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 21, 17, 32, 525372)),
        ),
    ]
