# Generated by Django 5.2.4 on 2025-08-20 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_remove_attendancesession_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 22, 30, 49, 391278)),
        ),
    ]
