# Generated by Django 5.2.4 on 2025-08-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
        migrations.AddField(
            model_name='student',
            name='Field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
