# Generated by Django 5.2.4 on 2025-08-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='target_roles',
            field=models.CharField(choices=[('all', 'All Users'), ('student', 'Students Only'), ('mentor', 'Mentors Only'), ('admin staff', 'admin staff only')], default='all', max_length=20),
        ),
    ]
